#!/usr/bin/env python

import time, webbrowser,socket 
from selenium import webdriver  

# Pega o navegador Utilizado 
driver = webdriver.Chrome('/home/gnu32/Área de Trabalho/chromedriver') 

def pegaNumero():
	# Pega destinatario pelo titulo do nome 
	pegaNumero = driver.find_element_by_xpath('//*[@id="pg-target"]/div[2]/div[2]/div/strong[3]').text
	pegaNumero = pegaNumero.replace(")", "")  
	pegaNumero = pegaNumero.replace("(", "")  
	pegaNumero = pegaNumero.replace("-", "")  
	pegaNumero = pegaNumero.replace(" ", "")  
	print("55" + pegaNumero)

 
arquivo = open('lista.txt', 'r')
texto = arquivo.readlines()
for linha in texto :
	try:
		driver.get(linha)  
		pegaNumero()
	except:
		print("nao deu")
