#!/usr/bin/env python

import time, webbrowser,socket 
from selenium import webdriver  



def pegaNumero():
	# Pega destinatario pelo titulo do nome 
	pegaNumero = driver.find_element_by_xpath('//*[@id="pg-target"]/div[2]/div[2]/div/strong[3]').text
	pegaNumero = pegaNumero.replace(")", "")  
	pegaNumero = pegaNumero.replace("(", "")  
	pegaNumero = pegaNumero.replace("-", "")  
	pegaNumero = pegaNumero.replace(" ", "")  
	print("55" + pegaNumero)

# Pega o navegador Utilizado 
driver = webdriver.Chrome()
driver.get('https://autocarro.com.br/unidus')
pegaNumero()
 
